Repository the-nexim/nanolib, pull requests merged in 2025-01, with the labels that each got.

#28 feat(typescript-config): add new configuration
  lerna.json
  packages/alpine/tsconfig.json
  packages/element/tsconfig.json
  packages/google-analytics/tsconfig.json
  packages/service-worker/tsconfig.json
  packages/typescript-config/README.md
  packages/typescript-config/package.json
  packages/typescript-config/tsconfig.base.json
  packages/typescript-config/tsconfig.browser.app.json
  packages/typescript-config/tsconfig.browser.lib.json
  packages/typescript-config/tsconfig.node.app.json
  packages/typescript-config/tsconfig.node.lib.json
  tsconfig.json
  yarn.lock
Labels: new-feature

#30 refactor: update output paths in package.json
  packages/alpine/package.json
Labels: bugfix

#29 feat: new `financial-calculating`
  README.md
  packages/financial-calculate/LICENSE
  packages/financial-calculate/README.md
  packages/financial-calculate/package.json
  packages/financial-calculate/src/main.test.js
  packages/financial-calculate/src/main.ts
  packages/financial-calculate/tsconfig.json
  yarn.lock
Labels: new-feature

#32 fix: check for service worker support before registration
  packages/service-worker/src/main.ts
Labels: bugfix

#33 feat(financial-calculating): add `calculateDiscountParentage` method
  packages/financial-calculate/README.md
  packages/financial-calculate/src/main.test.js
  packages/financial-calculate/src/main.ts
Labels: new-feature

#34 docs(alpine): auto generate documentation using typedoc
  .nvmrc
  .yarnrc.yml
  packages/alpine/README.md
  packages/alpine/package.json
  packages/alpine/src/store/store-generator.ts
  packages/alpine/src/store/store-with-backup.ts
  packages/alpine/src/store/store.ts
  packages/alpine/typedoc.json
  yarn.lock
Labels: documentation

#36 docs: adding typedoc
  package.json
  packages/element/package.json
  packages/element/typedoc.json
  packages/financial-calculate/package.json
  packages/financial-calculate/typedoc.json
  packages/google-analytics/package.json
  packages/google-analytics/typedoc.json
  packages/service-worker/package.json
  packages/service-worker/typedoc.json
  yarn.lock
Labels: documentation

#37 docs: generate documations
  .yarnrc.yml
  packages/alpine/package.json
  packages/alpine/tsdoc.json
  packages/alpine/typedoc.json
  packages/element/README.md
  packages/element/docs/README.md
  packages/element/docs/functions/LightDomMixin.md
  packages/element/docs/functions/LoggerMixin.md
  packages/element/docs/interfaces/LoggerMixinInterface.md
  packages/element/package.json
  packages/element/src/mixin/light-dom.ts
  packages/element/src/mixin/logging.ts
  packages/element/tsdoc.json
  packages/element/typedoc.json
  packages/financial-calculate/README.md
  packages/financial-calculate/docs/README.md
  packages/financial-calculate/docs/functions/calculateDiscountAmount.md
  packages/financial-calculate/docs/functions/calculateDiscountedPrice.md
  packages/financial-calculate/docs/functions/calculatePercentageDiscount.md
  packages/financial-calculate/docs/functions/calculatePercentageProfit.md
  packages/financial-calculate/package.json
  packages/financial-calculate/src/main.ts
  packages/financial-calculate/tsdoc.json
  packages/financial-calculate/typedoc.json
  packages/google-analytics/README.md
  packages/google-analytics/docs/README.md
  packages/google-analytics/docs/functions/initializeGoogleAnalytics.md
  packages/google-analytics/package.json
  packages/google-analytics/src/main.ts
  packages/google-analytics/tsdoc.json
  packages/google-analytics/typedoc.json
  packages/service-worker/README.md
  packages/service-worker/docs/README.md
  packages/service-worker/docs/functions/registerServiceWorker.md
  packages/service-worker/docs/type-aliases/ServiceWorkerEvent.md
  packages/service-worker/docs/variables/serviceWorkerSignal.md
  packages/service-worker/package.json
  packages/service-worker/src/main.ts
  packages/service-worker/tsdoc.json
  packages/service-worker/typedoc.json
  yarn.lock
Labels: documentation

#40 feat(service-worker): add periodic update checks for service worker
  package.json
  packages/element/package.json
  packages/financial-calculate/package.json
  packages/google-analytics/package.json
  packages/service-worker/docs/functions/registerServiceWorker.md
  packages/service-worker/docs/type-aliases/ServiceWorkerEvent.md
  packages/service-worker/package.json
  packages/service-worker/src/main.ts
  yarn.lock
Labels: new-feature

#22 refactor(eslint)!: migrate to eslint v9
  .eslintignore
  .eslintrc.json
  .github/dependabot.yml
  .vscode/settings.json
  .yarn/sdks/eslint/lib/universal.js
  .yarn/sdks/eslint/package.json
  .yarn/sdks/typescript/package.json
  .yarnrc.yml
  eslint.config.mjs
  package.json
  packages/alpine/docs/classes/AlpineStore.md
  packages/alpine/docs/classes/AlpineStoreWithBackup.md
  packages/alpine/docs/functions/alpineStoreGenerator.md
  packages/alpine/src/main.ts
  packages/alpine/src/store/store-generator.ts
  packages/alpine/src/store/store-with-backup.ts
  packages/alpine/src/store/store.ts
  packages/alpine/tsconfig.json
  packages/element/docs/functions/LightDomMixin.md
  packages/element/docs/functions/LoggerMixin.md
  packages/element/src/main.ts
  packages/element/src/mixin/light-dom.ts
  packages/element/src/mixin/logging.ts
  packages/element/tsconfig.json
  packages/eslint-config/README.md
  packages/eslint-config/eslint-config.cjs
  packages/eslint-config/package.json
  packages/eslint-config/src/lib/extended-config.ts
  packages/eslint-config/src/lib/javascript-config.ts
  packages/eslint-config/src/lib/typescript-config.ts
  packages/eslint-config/src/main.ts
  packages/eslint-config/tsconfig.json
  packages/financial-calculate/src/main.test.js
  packages/financial-calculate/src/main.ts
  packages/financial-calculate/tsconfig.json
  packages/google-analytics/docs/functions/initializeGoogleAnalytics.md
  packages/google-analytics/src/main.ts
  packages/google-analytics/tsconfig.json
  packages/prettier-config/package.json
  packages/prettier-config/prettier.config.cjs
  packages/service-worker/docs/functions/registerServiceWorker.md
  packages/service-worker/docs/variables/serviceWorkerSignal.md
  packages/service-worker/src/main.ts
  packages/service-worker/tsconfig.json
  yarn.lock
Labels: breaking-change, enhancement

#42 feat(eleventy): import from web-application-toolkit
  packages/eleventy-config/CHANGELOG.md
  packages/eleventy-config/LICENSE
  packages/eleventy-config/README.md
  packages/eleventy-config/package.json
  packages/eleventy-config/src/lib/eleventy-config.ts
  packages/eleventy-config/src/lib/font.ts
  packages/eleventy-config/src/lib/logger.ts
  packages/eleventy-config/src/lib/minify-html.ts
  packages/eleventy-config/src/lib/postcss.ts
  packages/eleventy-config/src/lib/util/trim.ts
  packages/eleventy-config/src/lib/workbox.ts
  packages/eleventy-config/src/main.test.js
  packages/eleventy-config/src/main.ts
  packages/eleventy-config/tsconfig.json
  yarn.lock
Labels: new-feature

#45 lint: Make Happy
  packages/eleventy-config/README.md
  packages/eleventy-config/src/lib/eleventy-config.ts
  packages/eleventy-config/src/lib/font.ts
  packages/eleventy-config/src/lib/logger.ts
  packages/eleventy-config/src/lib/minify-html.ts
  packages/eleventy-config/src/lib/postcss.ts
  packages/eleventy-config/src/lib/workbox.ts
  packages/eleventy-config/src/main.ts
Labels: bugfix
